# host-fakedate (package/fakedate/fakedate.mk): a `date` that honours SOURCE_DATE_EPOCH.
#   $(INSTALL) -D -m 755 package/fakedate/fakedate $(HOST_DIR)/bin/date
load("//br2:rules.bzl", "br2_dep", "BR2_STAMPS_HOST", "br2_native_package")

br2_native_package(
    name = "host-fakedate",
    pkg = "host-fakedate",
    bdir = "buildroot-src/package/fakedate",
    pkg_inputs = "//buildroot-src/package/fakedate:inputs",
    stamp_dir = "build/host-fakedate",
    stamps = BR2_STAMPS_HOST,
    host_install = {"bin/date": "//buildroot-src/package/fakedate:file.fakedate"},
    deps = [
        br2_dep("host-skeleton", "//buildroot-src/package/skeleton:host-skeleton"),
    ],
    visibility = ["PUBLIC"],
)
